(function(){
if (typeof window !== "undefined" && window.ITEMS) return;
// Content model for the Dubai page. Chapters in display order; items ranked within each.
// dated: {d:'24', m:'OCT', w:'SAT'} -> 24c stamped treatment
// ahead: 'concrete reason' -> 27b book-ahead treatment
// eyebrow: only where it genuinely adds something (26a); otherwise omitted (26c)

const CHAPTERS = [
  { key: 'loud',       name: 'Nights that go loud' },
  { key: 'strange',    name: 'Genuinely strange' },
  { key: 'dinners',    name: 'Long dinners' },
  { key: 'takehome',   name: "Things we'd take home" },
  { key: 'cooking',    name: 'Cooking and drinking' },
  { key: 'getgood',    name: 'Something to get good at' },
  { key: 'adrenaline', name: 'Adrenaline' },
  { key: 'rides',      name: 'Rides and slides' },
  { key: 'wandering',  name: 'Wandering and buying things' },
  { key: 'quiet',      name: 'Quiet and dark' },
  { key: 'elsewhere',  name: 'Whole days elsewhere' }
];

const ITEMS = [
  // ── Nights that go loud ────────────────────────────────────────────────
  { id:'elrow', ch:'loud', name:'elrow Nowmads', blurb:"Confetti, actors, and scenery that makes no sense at all. It's the one night on the calendar that's as much theatre as it is a party — I've wanted to see one for years.", when:'Doors 16:00', where:'Media City Amphitheatre', dated:{d:'24',m:'OCT',w:'SAT',on:'2026-10-24'}, cta:'Join the circus', book:'https://dubai.platinumlist.net/event-tickets/elrow-dubai', site:'https://elrow.com/', photos:5 },
  { id:'carlcox', ch:'loud', name:'Carl Cox at Playa Pacha', blurb:"The season opener, outdoors, right on the water. He has been doing this longer than either of us has been going out and still does it better than almost anyone.", when:'From 19:00 · 21+', where:'FIVE LUXE, JBR', dated:{d:'09',m:'OCT',w:'FRI',on:'2026-10-09'}, cta:'Get on the list', book:'https://www.ticketmaster.ae/venue/pacha-icons-five-luxe-jbr-dubai-tickets/lux/805', site:'https://luxejbr.fivehotelsandresorts.com/experience-five/', photos:4 },
  { id:'sonnyfodera', ch:'loud', name:'Sonny Fodera', blurb:"The night after Carl Cox, same stretch of beach. If we only want one of the two, this is the softer, more melodic one — and getting in before nine is cheaper.", when:'From 19:00 · 21+', where:'Playa Pacha, JBR', dated:{d:'10',m:'OCT',w:'SAT',on:'2026-10-10'}, cta:'Take me to the beach', book:'https://www.ticketmaster.ae/venue/pacha-icons-five-luxe-jbr-dubai-tickets/lux/805', photos:3 },
  { id:'adamport', ch:'loud', name:'Adam Port', blurb:"Keinemusik, on Halloween, outdoors. Hypnotic rather than hard — the kind of set you can actually talk over at the edges and still feel in your chest at the front.", when:'From 19:00 · 21+', where:'FIVE LUXE, JBR', dated:{d:'31',m:'OCT',w:'SAT',on:'2026-10-31'}, cta:'Halloween, sorted', book:'https://www.ticketmaster.ae/venue/pacha-icons-five-luxe-jbr-dubai-tickets/lux/805', photos:3 },
  { id:'untold', ch:'loud', name:'UNTOLD Dubai', blurb:"Four nights, enormous stages, and the biggest thing happening in the city all autumn. We'd only need to do one night of it to get the idea.", when:'Four nights', where:'Dubai Parks & Resorts', dated:{d:'5–8',m:'NOV',w:'THU',on:'2026-11-05'}, ahead:'Early-bird passes go first', cta:'Get the wristbands', site:'https://www.untold.ae/', photos:5 },
  { id:'atb', ch:'loud', name:'ATB, Solarstone & Steve Allen', blurb:"Proper old-school trance, three deep. Completely unfashionable and completely wonderful, and it's the first big night after I land.", when:'Doors 20:00', where:'The Agenda, Media City', dated:{d:'05',m:'SEP',w:'SAT',on:'2026-09-05'}, cta:'Take me back to 2004', book:'https://dubai.platinumlist.net/event-tickets/105150/the-legends-of-trans-atb', photos:2 },
  { id:'oakenfold', ch:'loud', name:'Paul Oakenfold & Markus Schulz', blurb:"The second trance night, with Richard Durand as well. If the September one goes well we already know we like the room.", when:'Doors 20:00', where:'The Agenda, Media City', dated:{d:'18',m:'SEP',w:'FRI',on:'2026-09-18'}, cta:'One more trance night', book:'https://dubai.platinumlist.net/event-tickets/105326/the-legends-of-trans-paul-oakenfold', photos:2 },
  { id:'lostfreq', ch:'loud', name:'Lost Frequencies at Bohemia', blurb:"The Palm season opening. More crossover than the Pacha nights and considerably easier to get into — a good one if we want a night out without committing to a whole festival.", when:'From 19:00', where:'FIVE Palm Jumeirah', dated:{d:'03',m:'OCT',w:'SAT',on:'2026-10-03'}, cta:'Open the season', site:'https://palmjumeirah.fivehotelsandresorts.com/', photos:3 },
  { id:'inthepark', ch:'loud', name:'In the Park', blurb:"An outdoor multi-act afternoon the day after elrow. Cheap, unserious, and exactly the right way to spend a Sunday when we're already wrecked.", when:'Doors 14:00', where:'Media City Amphitheatre', dated:{d:'25',m:'OCT',w:'SUN',on:'2026-10-25'}, cta:'Sunday, sorted', book:'https://dubai.platinumlist.net/event-tickets/pub-in-the-park', photos:3 },
  { id:'stardom', ch:'loud', name:'STARDOM Nightfall', blurb:"A superyacht out of the Marina with a DJ, food and the skyline going past. The music is atmosphere rather than the point — but as an evening it's hard to beat.", eyebrow:'Four hours on the water', when:'Sunset departures', where:'Dubai Marina', ahead:'Boats sell out at weekends', cta:'Get us on the boat', book:'https://xclusiveyachts.com/super-yacht-experience-dubai/', site:'https://xclusiveyachts.com/yacht-party-dubai/', photos:4 },
  { id:'sohogarden', ch:'loud', name:'Soho Garden, HIVE and CODE', blurb:"Three rooms on one Meydan site with a different lineup every week. The one to check when we want to go out and haven't planned anything.", when:'Weekly', where:'Meydan', site:'https://sohogardendxb.com/', ig:'https://www.instagram.com/sohogardendxb/', cta:'See who\'s playing', photos:3 },
  { id:'ushuaia', ch:'loud', name:'Ushuaïa Dubai Harbour', blurb:"The Ibiza export, open-air, right at the harbour. Worth watching the calendar for once the season properly starts.", when:'Seasonal', where:'Dubai Harbour', site:'https://theushuaiaexperience.com/', cta:'Check the season', photos:3 },
  { id:'terrasolis', ch:'loud', name:'Terra Solis', blurb:"Tomorrowland's desert outpost — pool by day, stage by night, an hour from the city. Best in October when it cools down enough to stay all day.", when:'Seasonal', where:'Dubai desert', site:'https://terrasolisdubai.com/', cta:'Escape to the dunes', photos:4 },
  { id:'honeycomb', ch:'loud', name:'Honeycomb Hi-Fi', blurb:"A proper listening bar — enormous speakers, records played all the way through, and nobody shouting. This is the one I want to make our regular place.", eyebrow:'You can hear each other', when:'Most evenings', where:'Pullman Downtown', site:'https://honeycombhifi.com/', ig:'https://www.instagram.com/honeycombhifi/', cta:'Find our table', photos:4 },
  { id:'rooftops', ch:'loud', name:'Cavo and The Penthouse', blurb:"Rooftops for when we want a view and a drink rather than a night out. Low commitment, and both are easy to walk away from early.", when:'Evenings', where:'Business Bay & Palm', cta:'Find a view', photos:3 },
  { id:'pawnshop', ch:'loud', name:'Electric Pawn Shop', blurb:"Small, dark, loud in the good way. Somewhere between a bar and a club, and it never needs planning.", when:'Late', where:'Downtown', shot:'dark bar interior, neon, low light', cta:'Turn up late', photos:2 },

  // ── Genuinely strange ─────────────────────────────────────────────────
  { id:'laperle', ch:'strange', name:'La Perle', blurb:"Divers, aerialists, motorbikes, and a stage that floods on cue. It's the only permanent show of its kind here and the engineering alone is worth the ticket.", when:'Most evenings', where:'Al Habtoor City', cta:'Watch them fall', site:'https://laperle.com/en/', photos:5 },
  { id:'teamlab', ch:'strange', name:'teamLab Phenomena', blurb:"A whole building of rooms that change because you walked into them. The single best thing on this list and worth the drive to Abu Dhabi on its own.", eyebrow:'Wear something you can get wet', when:'Daily, timed entry', where:'Saadiyat, Abu Dhabi', cta:'Step inside', site:'https://www.teamlababudhabi.com/', photos:6 },
  { id:'krasota', ch:'strange', name:'KRASOTA', blurb:"Dinner staged as a play for twenty people, with a menu written to follow the acts. Ridiculous, expensive, and I think you'd love it.", eyebrow:'Twenty seats, one story', when:'Evenings', where:'Address Downtown', ahead:'Twenty seats a sitting', cta:'Reserve two of twenty', site:'https://krasota.art/en/about', photos:4 },
  { id:'aya', ch:'strange', name:'AYA Universe', blurb:"Twelve rooms of light and projection you walk through rather than look at. Less clever than teamLab but a much easier evening — it's in a mall.", when:'Daily', where:'WAFI City', cta:'Walk into the light', site:'https://www.aya-universe.com/', photos:3 },
  { id:'arte', ch:'strange', name:'ARTE Museum', blurb:"Enormous projected landscapes with a tea room in the middle of it. Half an hour of it is genuinely lovely; two hours would be too much.", when:'Daily', where:'Dubai Mall', cta:'Wander in', site:'https://dubai.artemuseum.com/', photos:2 },
  { id:'toda', ch:'strange', name:'Theatre of Digital Art', blurb:"A rotating programme — sometimes Van Gogh, sometimes something far odder. Worth checking what's running before we commit.", when:'Rotating', where:'Souk Madinat', cta:'See what\'s showing', site:'https://toda.ae/', photos:3 },
  { id:'houseofhype', ch:'strange', name:'House of Hype', blurb:"Frankly a series of rooms built to be photographed in, and completely unembarrassed about it. Go in the right mood and it's very funny.", when:'Daily', where:'Dubai Mall', cta:'Be ridiculous with me', site:'https://houseofhype.com/dubai/', photos:3 },
  { id:'chaoskarts', ch:'strange', name:'Chaos Karts', blurb:"Go-karts in a blacked-out warehouse with the track projected onto the floor, Mario Kart style. Absurd, and I fully intend to lose.", eyebrow:'The track is projected, not painted', when:'Daily', where:'Al Quoz', cta:'Start your engines', site:'https://chaoskarts.ae/', photos:4 },
  { id:'motf', ch:'strange', name:'Museum of the Future', blurb:"More of a building than a museum, and the building is the reason to go. Book a timed slot or you won't get in.", when:'Daily', where:'Trade Centre', ahead:'Timed slots sell out days ahead', cta:'Visit the future', site:'https://museumofthefuture.ae/', photos:4 },
  { id:'playhouse', ch:'strange', name:'Courtyard Playhouse', blurb:"Unscripted improv in a tiny Al Quoz theatre, cheap and often terrible in the best way. Also where I'd take a class if we get bored.", when:'Weekly', where:'Al Quoz', site:'https://courtyardplayhouse.com/', shot:'small black-box theatre stage', cta:'See who\'s improvising', photos:2 },
  { id:'designweek', ch:'strange', name:'Dubai Design Week', blurb:"Installations across the whole design district, most of it free to walk around. It lands in my last week here, which feels like a decent way to finish.", when:'Six days', where:'Dubai Design District', dated:{d:'3–8',m:'NOV',w:'TUE',on:'2026-11-03'}, site:'https://www.dubaidesignweek.ae/', cta:'See the programme', photos:4 },
  { id:'downtowndesign', ch:'strange', name:'Downtown Design', blurb:"The trade fair inside Design Week — furniture, objects, a lot of very expensive chairs. Worth an afternoon if the installations grab us.", when:'Five days', where:'Dubai Design District', dated:{d:'4–8',m:'NOV',w:'WED',on:'2026-11-04'}, site:'https://www.downtowndesign.com/', cta:'See the fair', photos:3 },
  { id:'alwasl', ch:'strange', name:'Al Wasl Plaza projections', blurb:"The dome at Expo City turns into a 360-degree screen after dark. Free, and worth timing a walk around to catch.", when:'Programme-dependent', where:'Expo City', cta:'Catch the dome', photos:3 },
  { id:'lepetitchef', ch:'strange', name:'Le Petit Chef', blurb:"A tiny animated chef projected onto the tablecloth who cooks your dinner in front of you. Completely silly. I'd go.", when:'Evenings', where:'Various hotels', cta:'Meet the little chef', site:'https://lepetitchef.com/', photos:3 },

  // ── Long dinners ──────────────────────────────────────────────────────
  { id:'moonrise', ch:'dinners', name:'Moonrise', blurb:"Eight seats on a rooftop in Satwa and a menu that changes when the chef feels like it. Of everything on this list, this is the meal I most want to have with you.", eyebrow:'Eight seats on a rooftop', when:'Evenings', where:'Al Satwa', ahead:'Eight seats a night', cta:'Claim two of eight', site:'https://www.moon-rise.xyz/', photos:3 },
  { id:'ossiano', ch:'dinners', name:'Ossiano', blurb:"Dinner against the aquarium wall at Atlantis, with rays going past behind your head. It should be tacky and somehow isn't.", when:'Evenings', where:'Atlantis The Palm', ahead:'Window tables go weeks out', cta:'Ask for a window', site:'https://ossiano.info/', photos:2 },
  { id:'almahara', ch:'dinners', name:"L'Olivo at Al Mahara", blurb:"The other aquarium restaurant, inside the Burj Al Arab, and the more formal of the two. Worth it once for the room.", when:'Evenings', where:'Burj Al Arab', cta:'Dress up properly', site:'https://www.jumeirah.com/en/dine/dubai/burj-al-arab-lolivo-at-al-mahara', photos:3 },
  { id:'dits', ch:'dinners', name:'Dinner in the Sky', blurb:"A table bolted to a platform and hoisted fifty metres up. The food is beside the point and we both know it.", eyebrow:'Fifty metres up, no floor', when:'Weather permitting', where:'Al Sufouh', cta:'Strap in for dinner', site:'https://dinnerinthesky.ae/', photos:3 },
  { id:'sevenpaintings', ch:'dinners', name:'Seven Paintings', blurb:"A tasting menu built around seven paintings, projected around the room while you eat. Far better value than the other immersive dinners.", when:'Evenings', where:'Business Bay', cta:'Book the gallery', site:'https://www.dinnertales.com/', photos:3 },
  { id:'thepods', ch:'dinners', name:'The Pods', blurb:"Private glass pods on the water at Bluewaters, one table each. Quiet, a bit silly, and completely undisturbed.", when:'Evenings', where:'Bluewaters Island', cta:'Take a pod for two', site:'https://thepodsdubai.com/', photos:3 },
  { id:'supperclubs', ch:'dinners', name:'Secret supper clubs', blurb:"Dubai has a real underground supper-club scene that announces itself a week out and vanishes. Worth following a couple of accounts and pouncing.", when:'Announced late', where:'Various', shot:'one long candlelit table, dinner party', cta:'Find the next one', photos:2 },

  // ── Things we'd take home ─────────────────────────────────────────────
  { id:'lecole', ch:'takehome', name:"L'ÉCOLE · the jeweller's bench", blurb:"Two hours at a real jeweller's bench — sculpting wax, sawing metal, setting a stone. Van Cleef run it, and it is startlingly hands-on for something with that name on the door.", eyebrow:'A real bench, real tools', when:'2 hours', where:'Dubai Mall', ahead:'Small classes, published dates', cta:'Get on the bench', site:'https://www.lecolevancleefarpels.com/me/en/trying-out-jewelers-techniques-course-me', photos:4 },
  { id:'cyanotype', ch:'takehome', name:'Cyanotype and zine-making', blurb:"Printing with sunlight instead of a camera, then folding and binding the results into a small book. You'd leave with something we made in an afternoon.", when:'One session', where:'Tashkeel, Al Quoz', dated:{d:'15',m:'AUG',w:'SAT',on:'2026-08-15'}, cta:'Print with sunlight', site:'https://tashkeel.org/workshops/cyanotype-printing-zine-making', ig:'https://www.instagram.com/tashkeelstudio/', photos:3 },
  { id:'chipcarving', ch:'takehome', name:'Chip carving, three sessions', blurb:"Decorative woodcarving across three evenings, ending with letters and borders. The only proper short course I found that actually builds on itself.", when:'Three sessions', where:'Tashkeel, Al Quoz', ahead:'Runs as a fixed series', cta:'Sign us up for three', site:'https://tashkeel.org/workshops/chip-carving-letters-and-patters-series', photos:3 },
  { id:'limba', ch:'takehome', name:'Pottery on the wheel', blurb:"Ninety minutes on the wheel, and they fire and glaze whatever you make so you actually get it back. I will be worse at this than you.", eyebrow:'You keep the bowl', when:'90 minutes', where:'Limba Studio, Al Quoz', cta:'Get our hands dirty', site:'https://limbaceramics.com/pottery-on-the-wheel/', photos:4 },
  { id:'slab', ch:'takehome', name:'Slab · wheel throwing', blurb:"The other pottery studio, and they'll do a single class rather than making you sign up for a term. Smaller groups.", when:'One class', where:'Al Quoz', cta:'Throw something', site:'https://slabceramics.ae/class/wheel-throwing/', photos:3 },
  { id:'oolalab', ch:'takehome', name:'Oo La Lab · design a scent', blurb:"A private session building a fragrance from raw materials, and you walk out with fifty millilitres of it. We should make separate ones — the contrast is the fun part.", eyebrow:'You leave with 50ml of it', when:'Private session', where:'Confirm at checkout', ahead:'Book one to two weeks out', cta:'Bottle something', site:'https://uae.oola-lab.com/products/dubai-fragrance-design-mixology-private-session', photos:4 },
  { id:'mirzam', ch:'takehome', name:'Mirzam chocolate workshop', blurb:"A bean-to-bar factory in Al Quoz that runs tastings and making sessions, and smells extraordinary from the street.", when:'Scheduled', where:'Alserkal Avenue', cta:'Follow the smell', site:'https://mirzam.com/', photos:3 },
  { id:'procreate', ch:'takehome', name:'Procreate fashion illustration', blurb:"Three sessions drawing on an iPad, aimed squarely at fashion. Given what you do for a living this might be either perfect or insulting.", when:'Three sessions', where:'Tashkeel, Al Quoz', cta:'Draw with me', site:'https://tashkeel.org/workshops/procreate-fashion-illustration', shot:'iPad and stylus, fashion sketch in progress', photos:2 },
  { id:'gemology', ch:'takehome', name:'Introduction to gemstones', blurb:"Two hours learning to actually look at stones — what makes one better than another. The four-hour version goes deeper.", when:'2 or 4 hours', where:'Dubai Mall', cta:'Learn to spot a good one', site:'https://www.lecolevancleefarpels.com/me/en/world-gemstones/introduction-gemology-2-hrs', photos:3 },
  { id:'makerspace', ch:'takehome', name:'Design Week Maker Space', blurb:"Drop-in workshops running through Design Week in November. Programme lands closer to the time.", when:'During Design Week', where:'Dubai Design District', site:'https://www.dubaidesignweek.ae/open-call-2026/workshops/', shot:'hands at a workbench, tools laid out', cta:'See what\'s running', photos:2 },

  // ── Cooking and drinking ──────────────────────────────────────────────
  { id:'topchef', ch:'cooking', name:'Top Chef · homemade pasta', blurb:"Two pasta dishes and a dessert, made by hand and then eaten at their table. It turns into dinner, which is exactly what a cooking class should do.", eyebrow:'The class becomes dinner', when:'~3 hours', where:'Al Quoz', ahead:'Classes are booked in advance', cta:'Roll the pasta', site:'https://www.topchefdubai.com/cooking-classes/', photos:4 },
  { id:'ruya', ch:'cooking', name:'Rüya · cocktail masterclass', blurb:"Turkish-inspired drinks in a very good-looking room, and you're already sitting somewhere worth staying for dinner afterwards.", when:'~2 hours', where:'Grosvenor House', cta:'Shake something up', site:'https://www.sevenrooms.com/experiences/ruyadubai/cocktail-masterclass-6148787157041152', photos:2 },
  { id:'patisserie', ch:'cooking', name:'French pâtisserie lab', blurb:"Apple tart, macarons and mignardise at Banyan Tree, with a starter and main built into the price. The most generous class I found.", when:'Half a day', where:'Banyan Tree, Bluewaters', ahead:'Runs on set dates', cta:'Make macarons badly', site:'https://www.banyantree.com/united-arab-emirates/dubai/experiences/french-patisserie-lab', photos:2 },
  { id:'rawbarista', ch:'cooking', name:'RAW Coffee · home barista', blurb:"Four hours of espresso and milk texturing, taught properly rather than as a café demo. Expensive, and I'd still do it.", when:'4 hours', where:'Al Quoz', cta:'Pull a proper shot', site:'https://rawcoffeecompany.com/products/home-barista', photos:3 },
  { id:'spicespoons', ch:'cooking', name:'Anantara · Spice Spoons', blurb:"Thai cooking on the Palm, starting with the market and ending with lunch. Slower and more social than the others.", when:'Half a day', where:'Anantara, The Palm', cta:'Start at the market', site:'https://www.anantara.com/en/palm-dubai/restaurants/spice-spoons', photos:3 },
  { id:'salonchocolat', ch:'cooking', name:'Salon du Chocolat', blurb:"Three days of chocolate, with hands-on pastry workshops running alongside the show. Book the workshop, not just the entry.", when:'Three days', where:'Dubai', dated:{d:'22–24',m:'SEP',w:'TUE',on:'2026-09-22'}, cta:'All the chocolate', site:'https://www.salonduchocolatdubai.com/', photos:3 },
  { id:'dimsum', ch:'cooking', name:'Dim sum masterclass', blurb:"Folding dumplings badly for two hours, then eating them. Same venue as the pâtisserie lab.", when:'~2 hours', where:'Banyan Tree, Bluewaters', cta:'Fold dumplings badly', site:'https://www.banyantree.com/united-arab-emirates/dubai/experiences/the-bamboo-basket-master-class', shot:'hands folding dumplings, bamboo steamer', photos:2 },

  // ── Something to get good at ──────────────────────────────────────────
  { id:'mtnextreme', ch:'getgood', name:'Mountain Extreme', blurb:"Bouldering, ropes and auto-belay under one roof — the only place here that does all of it properly. I want this to be our Tuesday habit rather than a one-off.", eyebrow:'The one that does everything', when:'Repeatable', where:'Al Quoz', cta:'Claim our Tuesdays', site:'https://www.mtnextreme.com/book-now', photos:4 },
  { id:'boulderzone', ch:'getgood', name:'Boulder Zone', blurb:"Bouldering only, and they do a couples pass that runs the length of my stay. Friendlier for a first go than the big gym.", when:'Repeatable', where:'Al Quoz', cta:'See the couples pass', site:'https://boulderzone.ae/offerings/', photos:3 },
  { id:'rockrepublic', ch:'getgood', name:'Rock Republic', blurb:"The best-value three-month membership in the city, if a bit further out. Worth a look before we commit anywhere.", when:'Repeatable', where:'Dubai Investment Park', cta:'Compare the price', site:'https://www.rockrepublicdubai.com/general-7', photos:2 },
  { id:'goclimb', ch:'getgood', name:'GoClimb', blurb:"Big, modern, and the setting changes often enough to stay interesting. The other serious bouldering option.", when:'Repeatable', where:'Dubai Investment Park', cta:'Check the setting', site:'https://goclimb.ae/pricing', photos:3 },
  { id:'thewall', ch:'getgood', name:'The Wall', blurb:"Small, central and cheap for a single evening. Good for a spontaneous hour rather than as a base.", when:'Evenings', where:'District One', cta:'Squeeze in an hour', site:'https://www.thewallclimbinggym.ae/bookings/', shot:'indoor climbing wall, coloured holds', photos:2 },
  { id:'kitesurf', ch:'getgood', name:'Kitesurf course', blurb:"A real multi-session course rather than a one-hour taster, which is the only way it actually sticks. Worth knowing you'll spend most of it in deep water.", eyebrow:'You end up swimming a lot', when:'Multi-session', where:'Kite Beach', cta:'Learn to fly a kite', site:'https://kitesurfschooldubai.com/', photos:2 },
  { id:'efoil', ch:'getgood', name:'E-foil lesson', blurb:"Flying a board above the water on a hydrofoil. Ludicrous the first time, and apparently most people get up within an hour.", when:'Mornings', where:'The Palm', cta:'Fly above the water', site:'https://seawake.ae/', photos:3 },
  { id:'smartgate', ch:'getgood', name:'Smart Gate · DJ trial', blurb:"One session on real Pioneer equipment to see whether it's for us, without signing up for the whole five-lesson course. Given how much of this list is dance floors, it felt right.", eyebrow:'One session, no course', when:'~90 minutes', where:'Business Bay', cta:'Let me try the decks', site:'https://smgtdj.com/school', photos:2 },
  { id:'jamesalex', ch:'getgood', name:'Salsa or bachata drop-in', blurb:"An hour, cheap, several beginner slots a week, no commitment. The lowest-risk thing on this entire page.", when:'Weekly, 1 hour', where:'Al Quoz', cta:'Teach me to dance', site:'https://jamesandalex.com/classes/adult-classes/', photos:2 },
  { id:'palais', ch:'getgood', name:'Palais de Danse · private trial', blurb:"A private first lesson — tango, salsa, ballroom, whatever we pick — with nobody else watching. Probably the sensible order: this, then the drop-in.", when:'Private hour', where:'Jumeirah', cta:'Just the two of us', site:'https://www.palaisdedanse.com/buy-class', photos:2 },
  { id:'gpp', ch:'getgood', name:'Smartphone photography', blurb:"Three hours on light, composition and editing, all shot on a phone. Selfishly, I'd like to get better at taking pictures of you.", when:'3 hours', where:'Alserkal Avenue', cta:'Take better pictures of you', site:'https://gulfphotoplus.com/products/smartphone-photography-editing', photos:3 },
  { id:'wakeboard', ch:'getgood', name:'Wakeboard or wakesurf', blurb:"Early morning, flat water, and a boat. Repeatable enough to get properly good over three months.", when:'Mornings', where:'Marina', cta:'Get behind the boat', site:'https://seawake.ae/', photos:3 },

  // ── Adrenaline ────────────────────────────────────────────────────────
  { id:'skydive', ch:'adrenaline', name:'Skydive the Palm', blurb:"The one everyone photographs, and for once the photograph undersells it. October, when the air is clear and the heat has broken.", eyebrow:'Tandem — you do nothing but fall', when:'Mornings, October', where:'Skydive Dubai, Marina', ahead:'Palm slots book out weeks ahead', cta:'Throw ourselves out', site:'https://www.skydivedubai.ae/experiences/tandem-skydive', photos:3 },
  { id:'xline', ch:'adrenaline', name:'XLine Dubai Marina', blurb:"The longest urban zipline in the world, straight down the middle of the Marina at eighty kilometres an hour. Ninety seconds, and you can do it side by side.", eyebrow:'Two lines, side by side', when:'Any clear day', where:'Dubai Marina', cta:'Race me down', site:'https://www.xdubai.com/x-line', photos:3 },
  { id:'jaisflight', ch:'adrenaline', name:'Jais Flight', blurb:"The world's longest zipline, down a mountain in Ras Al Khaimah, flown lying flat. A proper day out rather than an afternoon.", when:'October onward', where:'Jebel Jais, RAK', cta:'Fly the mountain', site:'https://visitjebeljais.com/adrenaline/jais-flight/', photos:4 },
  { id:'viaferrata', ch:'adrenaline', name:'Jais Via Ferrata', blurb:"A cabled route across the mountain face — clipped in the whole way, so it's exposure rather than danger. My favourite kind of frightening.", when:'October onward', where:'Jebel Jais, RAK', cta:'Clip in with me', site:'https://visitjebeljais.com/adrenaline/jais-via-ferrata/', photos:3 },
  { id:'waterkarting', ch:'adrenaline', name:'Water karting', blurb:"Jet-propelled karts on a buoyed circuit out in Al Badayer. Short — pair it with the desert kart track or it's a long drive for ten minutes.", eyebrow:'Ten minutes, so pair it', when:'Short session', where:'Al Badayer, Sharjah', cta:'Start your engines', site:'https://monster-experience.com/go-karting-dubai/', photos:2 },
  { id:'ifly', ch:'adrenaline', name:'Indoor skydiving', blurb:"A vertical wind tunnel, so all the falling and none of the aeroplane. Also completely weather-proof, which matters in August.", when:'Any day', where:'Mirdif / Yas Island', cta:'Fall indoors', photos:3 },
  { id:'clymb', ch:'adrenaline', name:'CLYMB Abu Dhabi', blurb:"A forty-two-metre climbing wall and the world's biggest indoor skydiving chamber in one building. Pairs perfectly with teamLab on the same day.", when:'Day trip', where:'Yas Island, Abu Dhabi', cta:'Climb forty-two metres', site:'https://tickets.clymbabudhabi.com/climbing-experience', photos:4 },
  { id:'jetski', ch:'adrenaline', name:'Jet ski along the coast', blurb:"Half an hour past the Burj Al Arab with the city on one side. Life vests throughout, and you never leave the machine.", when:'Mornings', where:'JBR / Kite Beach', cta:'Open the throttle', photos:3 },
  { id:'flyboard', ch:'adrenaline', name:'Flyboard', blurb:"Standing on a jet of water two metres above the sea, being told to relax. Brief, hilarious, and much harder than it looks.", when:'Mornings', where:'JBR / The Palm', cta:'Hover, badly', photos:3 },
  { id:'parasail', ch:'adrenaline', name:'Parasailing', blurb:"Up off the back of a boat, over the water, in a harness. Calm rather than frightening — and you start and finish dry on the deck.", when:'Mornings', where:'JBR / The Palm', cta:'Go up on a string', photos:3 },
  { id:'xpark', ch:'adrenaline', name:'XPark', blurb:"Ropes courses, ninja lines and climbing frames on the beach, best after dark once it cools. Cheap and unserious.", when:'Evenings', where:'Kite Beach', shot:'beach ropes course at dusk', cta:'Play on the beach', photos:3 },

  // ── Rides and slides ──────────────────────────────────────────────────
  { id:'aquaventure', ch:'rides', name:'Aquaventure', blurb:"The biggest waterpark here by a distance, and better treated as somewhere we go three times than a single exhausting day. Vests everywhere, and the lazy river is genuinely lazy.", eyebrow:'Better three times than once', when:'Any day', where:'Atlantis, The Palm', cta:'Get the day pass', site:'https://www.atlantis.com/dubai/experiences', photos:5 },
  { id:'yaswaterworld', ch:'rides', name:'Yas Waterworld', blurb:"The best of the Abu Dhabi parks and the reason to make the drive. Pair it with Ferrari World the next day and stay on the island.", when:'Day trip', where:'Yas Island, Abu Dhabi', cta:'Plan the raid', site:'https://www.yaswaterworld.com/', photos:4 },
  { id:'imgworlds', ch:'rides', name:'IMG Worlds · Haunted Town', blurb:"Air-conditioned rides plus a full horror overlay through October, including a walk-through hotel with live actors. Weekday afternoon, and stay for the dark.", when:'October', where:'City of Arabia', dated:{d:'OCT',m:'2026',w:'ALL',on:'2026-10-01'}, cta:'Face the haunted hotel', site:'https://www.imgworlds.com/events', photos:4 },
  { id:'wildwadi', ch:'rides', name:'Wild Wadi', blurb:"Smaller and much more convenient than Aquaventure — arrive at opening, do the big four, leave after lunch.", when:'Half a day', where:'Jumeirah', cta:'Beat the queue', site:'https://www.wildwadi.com/en', photos:4 },
  { id:'aquafun', ch:'rides', name:'AquaFun', blurb:"An enormous inflatable obstacle course floating off JBR. Vests provided — though falling in is more or less the entire activity.", eyebrow:'Ninety minutes of real effort', when:'Mornings', where:'JBR', cta:'Fall in repeatedly', site:'https://www.aquafun.ae/', photos:3 },
  { id:'ferrariworld', ch:'rides', name:'Ferrari World', blurb:"Home of the fastest rollercoaster on earth, which does nought to two hundred in under five seconds. Indoors, so the heat is irrelevant.", when:'Day trip', where:'Yas Island, Abu Dhabi', cta:'Nought to two hundred', site:'https://www.ferrariworldabudhabi.com/en/Tickets/single-day-ticket', photos:4 },
  { id:'motiongate', ch:'rides', name:'Motiongate', blurb:"Worth it for one ride — a spinning coaster with a story built into it. Secondary unless they announce something for the autumn.", when:'Day out', where:'Dubai Parks & Resorts', cta:'Ride the spinner', site:'https://www.dubaiparksandresorts.com/en/motiongatetm-dubai', photos:3 },
  { id:'stormcoaster', ch:'rides', name:'The Storm Coaster', blurb:"A vertical-launch coaster that climbs fifty metres through the roof of a shopping mall. Ride it twice at seven, then go and have dinner.", eyebrow:'Ninety minutes, start to finish', when:'Evenings', where:'Dubai Hills Mall', cta:'Launch through the roof', site:'https://www.emaar.com/en/the-storm-coaster', photos:3 },
  { id:'skidubai', ch:'rides', name:'Ski Dubai', blurb:"Snow, indoors, in the desert, in August. Objectively absurd and I want to see your face.", when:'Any day', where:'Mall of the Emirates', cta:'Find snow in August', site:'https://www.skidxb.com/', photos:2 },
  { id:'seaworldad', ch:'rides', name:'SeaWorld Abu Dhabi', blurb:"Enormous aquarium architecture rather than rides. The calm option if we've already done Ferrari World.", when:'Day trip', where:'Yas Island, Abu Dhabi', cta:'See the big tank', site:'https://seaworldabudhabi.com/', photos:5 },

  // ── Wandering and buying things ───────────────────────────────────────
  { id:'olddubai', ch:'wandering', name:'Old Dubai, souk to abra', blurb:"Textiles, then the water taxi across the creek for a single dirham, then spice and perfume and gold. Go late in the day — it's the best few hours in the city and costs almost nothing.", eyebrow:'The crossing costs one dirham', when:'Late afternoon', where:'Deira & Bur Dubai', cta:'Cross for one dirham', site:'https://www.visitdubai.com/en/places-to-visit/dubai-gold-souk', photos:5 },
  { id:'alserkal', ch:'wandering', name:'Alserkal Avenue', blurb:"Galleries, independent fashion, vinyl, a chocolate factory and decent coffee, all in one warehouse compound. Three or four hours and the best Saturday afternoon here.", when:'Afternoons', where:'Al Quoz', site:'https://alserkal.online/', ig:'https://www.instagram.com/alserkalavenue/', cta:'Lose an afternoon', photos:2 },
  { id:'globalvillage', ch:'wandering', name:'Global Village', blurb:"Pavilions from dozens of countries, and it works if we treat it as a food and textile expedition rather than trying to see all of it. Pick four pavilions and ignore the rest.", when:'Evenings, from mid-Oct', where:'Sheikh Mohammed Bin Zayed Rd', dated:{d:'OCT',m:'ONWARD',w:'SEASON',on:'2026-10-15'}, cta:'Pick four pavilions', site:'https://www.globalvillage.ae/', photos:4 },
  { id:'artemarket', ch:'wandering', name:"ARTE, The Makers' Market", blurb:"Independent makers, rotating between venues most weekends. The Mercato dates are the nicer setting; Times Square is the better browse.", when:'Weekends', where:'Mercato / Times Square', dated:{d:'8 & 29',m:'AUG',w:'SAT',on:'2026-08-08'}, site:'https://arte.ae/market-dates/', cta:'See the market dates', photos:2 },
  { id:'greenplanet', ch:'wandering', name:'The Green Planet', blurb:"An indoor rainforest with three thousand plants and animals in it, ninety minutes end to end. A very easy date before dinner on City Walk.", when:'90 minutes', where:'City Walk', cta:'Step into the jungle', site:'https://thegreenplanetdubai.com/', photos:3 },
  { id:'comptoir', ch:'wandering', name:'Comptoir 102', blurb:"A Jumeirah villa that's half concept store and half café. Brunch, then an hour of browsing — not a destination, but a very good morning.", when:'Mornings', where:'Jumeirah', site:'https://comptoir102.com/pages/concept-store-jumeirah-dubai', cta:'Brunch, then browse', photos:2 },
  { id:'flipside', ch:'wandering', name:'The Flip Side', blurb:"A vinyl specialist in Alserkal that also runs listening sessions. Worth checking what's on before we go.", when:'Afternoons', where:'Alserkal Avenue', shot:'record crates, hands flicking through vinyl', cta:'Flick through the crates', photos:2 },
  { id:'theedit', ch:'wandering', name:'The Edit', blurb:"A concept space built around women-founded fashion, jewellery and beauty, with a matcha bar in it. Same compound as everything else.", when:'Afternoons', where:'Alserkal Avenue', site:'https://theeditdubai.com/pages/about-us', shot:'concept-store rail, styled interior', cta:'Have a proper look', photos:2 },
  { id:'ibnbattuta', ch:'wandering', name:'Ibn Battuta Mall', blurb:"Six courts themed on China, India, Persia, Egypt, Tunisia and Andalusia. Go for the architecture, which is genuinely strange, not the shops.", eyebrow:'Go for the ceilings', when:'An hour', where:'Jebel Ali', site:'https://www.ibnbattutamall.com/about-us', cta:'Go for the ceilings', photos:2 },
  { id:'fashionavenue', ch:'wandering', name:'Fashion Avenue', blurb:"The serious end of Dubai Mall. Weekday morning if we actually want to look at anything.", when:'Weekday mornings', where:'Dubai Mall', site:'https://thedubaimall.com/en/fashion-avenue', cta:'Window shop properly', photos:2 },
  { id:'fashiondome', ch:'wandering', name:'Fashion Dome', blurb:"Mall of the Emirates, and honestly more manageable than Dubai Mall for real shopping. Ninety minutes and then dinner.", when:'90 minutes', where:'Mall of the Emirates', site:'https://www.malloftheemirates.com/en/fashion-dome', shot:'luxury mall atrium, marble and light', cta:'Do it efficiently', photos:2 },
  { id:'outletvillage', ch:'wandering', name:'The Outlet Village', blurb:"Only worth it with a list, or as the back half of a Motiongate day. Otherwise it's a long way to go to be disappointed.", when:'With a plan', where:'Jebel Ali', site:'https://theoutletvillage.ae/en', shot:'Tuscan-style arcade interior', cta:'Bring a list', photos:2 },

  // ── Quiet and dark ────────────────────────────────────────────────────
  { id:'nest', ch:'quiet', name:'The Nest by Nara', blurb:"A private pod with a glass roof, out in the protected desert, with dinner beforehand. Properly dark and properly quiet, and this is the one I'd book first.", eyebrow:'A glass roof, and nothing for miles', when:'Overnight', where:'Al Marmoom Reserve', ahead:'Only a handful of pods', cta:'Book us a glass roof', site:'https://www.nara.ae/the-nest/', photos:5 },
  { id:'sonara', ch:'quiet', name:'Sonara Camp', blurb:"A set dinner in the dunes with live music low in the background — the opposite of the dune-bashing package. Works on its own or as the front half of the Nest.", when:'Evenings, Sep onward', where:'Al Marmoom Reserve', ahead:'Set sittings, limited covers', cta:'Set a table in the dunes', site:'https://www.nara.ae/sonara-camp-dubai/', photos:4 },
  { id:'balloon', ch:'quiet', name:'Balloon over the dunes', blurb:"Sunrise, silence, and the desert going gold underneath. One of the very few things here that is both spectacular and completely calm — and the season starts the week after I arrive.", eyebrow:'Season opens 26 September', when:'Sunrise', where:'Dubai Desert Conservation Reserve', ahead:'Weather cancels flights — book a backup day', cta:'Take us up at dawn', site:'https://uae.heroballoonflights.com/signature-experience', photos:3 },
  { id:'mleiha', ch:'quiet', name:'Mleiha stargazing', blurb:"An hour out of the city into Sharjah, where it gets genuinely dark. Telescopes, and dinner in the desert if we want it.", when:'Evenings, Sep onward', where:'Mleiha, Sharjah', cta:'Go find some dark', site:'https://www.discovermleiha.ae/', photos:2 },
  { id:'talise', ch:'quiet', name:'Talise Ottoman Spa', blurb:"A proper hammam, and then nothing else planned for the rest of the day. The recovery option after a heavy weekend.", when:'Half a day', where:'Jumeirah Zabeel Saray, The Palm', cta:'Book the hammam', site:'https://www.jumeirah.com/en/stay/dubai/jumeirah-zabeel-saray/wellness/talise-ottoman-spa', photos:3 },
  { id:'lovelakes', ch:'quiet', name:'Al Qudra and the Love Lakes', blurb:"Lakes cut into the desert an hour out, with flamingos and almost nobody there at dawn. Free, and the best cheap thing on this list.", eyebrow:'Costs nothing at all', when:'Sunrise or sunset', where:'Al Qudra', cta:'Drive out at dawn', photos:3 },
  { id:'yacht', ch:'quiet', name:'A boat at sunset', blurb:"A small charter rather than a party boat, out past the Palm as the light goes. Two of us and whoever is driving.", when:'Sunset', where:'Dubai Marina', cta:'Get us a small boat', photos:4 },
  { id:'opera', ch:'quiet', name:'Dubai Opera', blurb:"Whatever's on — opera, ballet, a candlelit string quartet doing film scores. Worth watching the calendar for one good night.", when:'Programme-dependent', where:'Downtown', cta:'See what\'s on', site:'https://www.dubaiopera.com/', photos:2 },
  { id:'kayaksunrise', ch:'quiet', name:'Kayak or paddleboard at sunrise', blurb:"Flat water, no wind, and the city waking up behind us. Vests as standard, and you can stand up the whole time if you'd rather.", when:'Sunrise', where:'Kite Beach / The Palm', cta:'Beat the sunrise', photos:2 },
  { id:'picnic', ch:'quiet', name:'A picnic somewhere with no lights', blurb:"Not really an activity so much as a plan. Buy things at the market in the morning, drive out in the evening, stay until it's cold.", when:'Sunset', where:'Desert or beach', shot:'blanket and lantern, desert at dusk', cta:'Pick a dark spot', photos:2 },

  // ── Whole days elsewhere ──────────────────────────────────────────────
  { id:'snoopy', ch:'elsewhere', name:'Snorkelling at Snoopy Island', blurb:"The east coast, two and a half hours away, where the water is actually clear. Shore entry into shallow water — you can stand up most of the way out, and there are turtles.", eyebrow:'Shallow, shore entry, no boat', when:'Day trip', where:'Al Aqah, Fujairah', cta:'Find the turtles', photos:4 },
  { id:'musandam', ch:'elsewhere', name:'Musandam by dhow', blurb:"A wooden boat through Omani fjords for the day, stopping to snorkel off the side in flat, sheltered water. Bring a passport — it's a border crossing.", eyebrow:'Passport needed — this is Oman', when:'Full day', where:'Dibba, Oman', ahead:'Confirm border rules before booking', cta:'Cross into Oman', site:'https://sheesabeach.com/liveaboard/', photos:5 },
  { id:'hatta', ch:'elsewhere', name:'Hatta', blurb:"Mountains, a green reservoir you can kayak on, and mountain-bike trails — ninety minutes from the flat. The most complete day trip in the emirate.", when:'Day trip, October', where:'Hatta', cta:'Plan the mountain day', site:'https://www.visithatta.com/en/things-to-do/hatta-wadi-hub', photos:5 },
  { id:'jebeljais', ch:'elsewhere', name:'Jebel Jais', blurb:"The highest mountain in the country, with a viewing platform, a restaurant at the top, and cold air. Worth staying a night in Ras Al Khaimah rather than driving back tired.", when:'Day or overnight', where:'Ras Al Khaimah', site:'https://visitjebeljais.com/', cta:'Head for the summit', photos:5 },
  { id:'abudhabiday', ch:'elsewhere', name:'A day in Abu Dhabi', blurb:"teamLab in the morning, CLYMB in the afternoon, and the drive stops feeling like a waste. The single best-value day out on this whole page.", eyebrow:'Two things, one drive', when:'Full day', where:'Yas & Saadiyat, Abu Dhabi', cta:'Plan the drive', site:'https://www.teamlababudhabi.com/en/plan-your-visit', photos:4 },
  { id:'yasraid', ch:'elsewhere', name:'Two days on Yas Island', blurb:"Yas Waterworld one day, Ferrari World the next, sleeping on the island in between. Only worth doing as a pair — one park doesn't justify the drive.", when:'Two days', where:'Yas Island, Abu Dhabi', ahead:'Hotel and both parks together', cta:'Book both parks', photos:4 },
  { id:'fujairah', ch:'elsewhere', name:'The east coast', blurb:"Right across the country to the Gulf of Oman — mountains on one side, actual clear sea on the other. Pair it with Snoopy Island and make a weekend.", when:'Weekend', where:'Fujairah', cta:'Cross the country', photos:4 },
  { id:'alain', ch:'elsewhere', name:'Al Ain oasis', blurb:"Date palms, falaj irrigation channels and shade — the oldest continuously inhabited place in the country. Cooler than the coast and almost empty.", when:'Day trip', where:'Al Ain', cta:'Find the shade', photos:3 }
];


if (typeof module !== "undefined") module.exports = { CHAPTERS, ITEMS };
if (typeof window !== "undefined") { window.CHAPTERS = CHAPTERS; window.ITEMS = ITEMS; }
})();
